repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
        name: Sort imports with isort

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
        args: ["-t", "py38", "-l", "100"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    - id: trailing-whitespace
    - id: check-executables-have-shebangs
    - id: requirements-txt-fixer

  - repo: https://github.com/PyCQA/doc8
    rev: 0.9.0a1
    hooks:
    - id: doc8
      name: Autoformat docs with doc8
      args: [--max-line-length, "100"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        name: Linting with flake8
        exclude: docs/conf.py
        additional_dependencies: [flake8-comprehensions, flake8-builtins, flake8-blind-except, flake8-bugbear, flake8-use-fstring]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.3
    hooks:
      - id: pyupgrade
        name: Upgrade syntax to python 3.6+ with pyupgrade
        args: [--py36-plus]

